# Generated by Django 4.2.7 on 2023-11-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=42)),
                ('Confirm_Password', models.CharField(max_length=42)),
            ],
        ),
    ]
