# Generated by Django 5.0.1 on 2024-01-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=42)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=42)),
                ('Confirm_Password', models.CharField(max_length=42)),
            ],
        ),
    ]
